### ISSUE TITLE
FYI, Robert Smallshire is also on GitHub ...

### ISSUE THREAD

**Issue by bitRAKE** [nmhancock/type-inferencing#1]
Reading the linked article from web.archive.org is very helpful, but might also be useful to link the author here on Github, imho. No idea why his blog is not responding.

https://github.com/rob-smallshire/hindley-milner-python

**Comment by nmhancock** [comment]
Hey, thanks for letting me know. I updated the README to link to his GitHub, if there's a better GitHub-specific way to link to his project please let me know.
